# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.8.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 619)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.coffeeView = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.coffeeView.setGeometry(QtCore.QRect(0, 0, 801, 541))
        self.coffeeView.setObjectName("coffeeView")
        self.coffeeView.setColumnCount(0)
        self.coffeeView.setRowCount(0)
        self.buttonAddUpdate = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonAddUpdate.setGeometry(QtCore.QRect(0, 540, 141, 28))
        self.buttonAddUpdate.setObjectName("buttonAddUpdate")
        self.buttonRefresh = QtWidgets.QPushButton(parent=self.centralwidget)
        self.buttonRefresh.setGeometry(QtCore.QRect(660, 540, 141, 28))
        self.buttonRefresh.setObjectName("buttonRefresh")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.buttonAddUpdate.setText(_translate("MainWindow", "Добавить/Изменить"))
        self.buttonRefresh.setText(_translate("MainWindow", "Обновить"))
